# Build and Task Haskell Program

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: ${{ matrix.resolver }} (${{ matrix.ghc }}/${{ matrix.cabal }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        ghc: ["9.12.2"]
        cabal: ["3.0.0.0"]
        os: [ubuntu-latest]
        resolver: [lts]
        # exclude:
        #   # GHC 8.8+ only works with cabal v3+
        #   - ghc: 8.8.3
        #     cabal: 2.4.1.0
    steps:
      - uses: actions/checkout@v3
      - name: Cache ~/.cabal/packages, ~/.cabal/store and dist-newstyle
        uses: actions/cache@v4
        with:
          path: |
            ~/.cabal/packages
            ~/.cabal/store
            dist-newstyle
          key: ${{ runner.os }}-${{ matrix.ghc }}-${{ hashFiles('**/*.cabal', '**/cabal.project', '**/cabal.project.freeze') }}
          restore-keys: ${{ runner.os }}-${{ matrix.ghc }}-

      - name: Setup Haskell
        uses: haskell-actions/setup@v2.8.2
        with:
          ghc-version: ${{ matrix.ghc }}
          cabal-version: ${{ matrix.cabal }}

      - name: Install dependencies
        run: |
          cabal update
          cabal install --only-dependencies

      - name: Build
        run: cabal build

      - name: Run tests
        run: cabal test
